services:
  - postgresql
  - redis-server
language: ruby
cache: bundler
rvm:
- 2.3.0
bundler_args: "--without=development"
env:
  global:
    - DATABASE_URL=postgres://localhost/slash_heroku_test
before_script:
- psql -c 'create database slash_heroku_test;' -U postgres
- bin/setup
script: bundle exec bin/cibuild
notifications:
  email: false
addons:
  postgresql: 9.4
